name: Test
on: [push, pull_request]
jobs:
  lint:
    runs-on: ["ubuntu-22.04"]
    name: lint
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: sudo apt-get update && sudo apt-get install -y curl gcc
      - run: curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.4.1 python3 -
      - run: poetry install --all-extras
      - run: poetry check
      - run: poetry run ruff check ./sqlargon
      - run: poetry run ruff format ./sqlargon --check
      - run: poetry run mypy ./sqlargon
      - run: poetry run deptry ./sqlargon
      - run: poetry run bandit -r ./sqlargon

  build-unix:
    timeout-minutes: 30
    strategy:
      matrix:
        os: ["ubuntu-22.04"]
        python: ["3.9", "3.10", "3.11", "3.12"]

    runs-on: ${{ matrix.os }}
    name: test on ${{ matrix.python }} - ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: sudo apt-get update && sudo apt-get install -y gcc curl
      - run: curl -sSL https://install.python-poetry.org | python3 -
      - run: poetry install --all-extras
      - run: poetry run pytest --cov=./sqlargon --cov-report=xml -v ./tests
